#!/usr/bin/env python3
"""Generate the _GUIDE_HTML block in relayshield_api.py from the markdown guides.

Run:    python3 build_guides.py
Check:  python3 build_guides.py --check   (exit 1 if the served HTML has drifted
        from the markdown; no writes -- this is the CI-safe mode)

WHY THIS EXISTS. The integration guides were maintained as two independent
copies: the markdown source, and a hand-pasted HTML string inside
relayshield_api.py served at /guides/<slug>. A comment above that block said
"regenerate from source", but no generator existed, so regenerating meant
pasting by hand and in practice nobody did.

The two copies drifted, and the drift was the dangerous direction. On
2026-08-15 the Sentinel guide was corrected against a live workspace: a fifth
ObservableKey value, "measured" replacing "derived, not measured", and
case-folding added to every malware-family query. Every one of those
corrections landed in the markdown only. The page customers actually read went
on shipping queries that silently under-match by ~68% while claiming the
queries had never been run. Only the metrics reconciliation reached both
copies, because that one was done with a script.

So: one source (the markdown), one renderer (build_blog.md_to_html, the same
one the blog uses), and a --check mode so the drift is caught rather than
rediscovered months later on a customer-facing page.
"""
import ast
import io
import json
import os
import sys

from build_blog import md_to_html

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.join(HERE, "relayshield_api.py")

# title and desc stay here rather than in the markdown: they are SEO surface
# (<title>, meta description, og:*, JSON-LD) and deliberately differ from the
# document's own H1, which reads as a sentence rather than a search query.
GUIDES = [
    {
        "slug": "elastic-security",
        "md": "elastic_security_integration_guide.md",
        "title": "Ingest RelayShield Threat Intelligence into Elastic Security",
        "desc": (
            "Configure Elastic's Custom Threat Intelligence integration against "
            "RelayShield's TAXII 2.1 feed. Includes measured ECS field mappings "
            "and Indicator Match rule setup."
        ),
    },
    {
        "slug": "microsoft-sentinel",
        "md": "sentinel_integration_guide.md",
        "title": "Ingest RelayShield Threat Intelligence into Microsoft Sentinel",
        "desc": (
            "Configure Sentinel's Threat Intelligence TAXII connector against "
            "RelayShield's STIX 2.1 feed. Includes the ThreatIntelIndicators "
            "schema, ObservableKey mappings, analytics rules and hunting queries."
        ),
    },
]

HEADER = """# Rendered integration guides. GENERATED by build_guides.py from the .md
# sources -- do not edit this block by hand, your edit will be overwritten.
# Regenerate with `python3 build_guides.py` after touching any guide markdown,
# and note that relayshield-api is a multi-file deploy.
"""


def render():
    """Build the {slug: {...}} mapping from the markdown sources."""
    guides = {}
    for g in GUIDES:
        path = os.path.join(HERE, g["md"])
        with io.open(path, encoding="utf-8") as fh:
            md = fh.read()
        guides[g["slug"]] = {
            "desc": g["desc"],
            "html": md_to_html(md),
            "title": g["title"],
        }
    # Sorted so a regeneration produces a stable diff rather than a reordering.
    return dict(sorted(guides.items()))


def render_block(guides):
    """Emit the source text of the _GUIDE_HTML assignment."""
    lines = ["_GUIDE_HTML = {"]
    for slug in guides:
        lines.append("%s: {" % json.dumps(slug))
        for key in ("desc", "html", "title"):
            comma = "," if key != "title" else ""
            lines.append("%s: %s%s" % (json.dumps(key), json.dumps(guides[slug][key]), comma))
        lines.append("},")
    # Drop the trailing comma on the last entry to match the previous formatting.
    lines[-1] = "}"
    lines.append("}")
    return "\n".join(lines)


def locate(src):
    """Return (start_line, end_line) 1-indexed bounds of the _GUIDE_HTML assignment."""
    for node in ast.parse(src).body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "_GUIDE_HTML":
            return node.lineno, node.end_lineno
    raise SystemExit("could not find the _GUIDE_HTML assignment in %s" % TARGET)


def splice(src, block):
    """Replace the _GUIDE_HTML assignment (and any comment header above it) with block."""
    lines = src.split("\n")
    start, end = locate(src)
    first = start - 1
    # Absorb the contiguous comment block directly above the assignment so the
    # regenerated header replaces the old hand-written one instead of stacking.
    while first > 0 and lines[first - 1].startswith("#"):
        first -= 1
    return "\n".join(lines[:first] + (HEADER + block).split("\n") + lines[end:])


def main():
    check = "--check" in sys.argv
    with io.open(TARGET, encoding="utf-8") as fh:
        src = fh.read()

    guides = render()
    updated = splice(src, render_block(guides))

    if updated == src:
        print("up to date: %d guides, no change to %s" % (len(guides), os.path.basename(TARGET)))
        return 0

    if check:
        sys.stderr.write(
            "DRIFT: the served HTML in %s does not match the markdown sources.\n"
            "Run `python3 build_guides.py` and redeploy relayshield-api.\n"
            % os.path.basename(TARGET)
        )
        return 1

    with io.open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(updated)
    for slug, g in guides.items():
        print("  %-20s %6d chars html" % (slug, len(g["html"])))
    print("wrote %s" % TARGET)
    return 0


if __name__ == "__main__":
    sys.exit(main())
