// RelayShield blog — self-hosted on infrastructure we control.
//
// Replaced the previous 7-line 301 to relayshield.hashnode.dev on 2026-07-29,
// after Hashnode's AutoMod repeatedly archived posts as "heavily promotional"
// and confirmed they could not be restored on the free tier. Slugs are
// preserved exactly so every link ever shared keeps resolving.
//
// Content lives in blog_posts.js, generated by build_blog.py. Do not hand-edit
// that file — re-run the builder instead.

import { POSTS } from "./blog_posts.js";
import { OG_PNG_BASE64 } from "./blog_og_image.js";
import { DEVELOPERS_OG_PNG_BASE64 } from "./developers_og_image.js";

const SITE = "https://blog.relayshield.net";
const NAME = "RelayShield Security Intelligence";
const TAGLINE =
  "Threat intelligence and credential exposure research from the marketplaces where credentials are actually sold.";

const BY_SLUG = new Map(POSTS.map((p) => [p.slug, p]));

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const fmtDate = (iso) => {
  const d = new Date(iso + "T00:00:00Z");
  return isNaN(d)
    ? iso
    : d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" });
};

// Byte-identical to the one relayshield_api.py serves at
// api.relayshield.net/favicon.svg. Kept as a literal in both rather than
// fetched, so neither origin's icon depends on the other being up.
const FAVICON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">' +
  '<rect width="64" height="64" rx="12" fill="#1a1035"/>' +
  '<path d="M32 8 54 16v16c0 13-9 21-22 24-13-3-22-11-22-24V16z" fill="#a855f7"/>' +
  '<path d="M32 12 50 18.5V32c0 11-7.5 17.5-18 20.5V12z" fill="#9333ea"/>' +
  '<path d="M21 32.5 28.5 40 44 24" fill="none" stroke="#f4f4e8" ' +
  'stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>' +
  '</svg>';

const CSS = `
:root{--bg:#0d0f14;--surface:#161a23;--border:#252b38;--text:#e8ecf4;--muted:#98a2b8;--accent:#6c63ff;--accent2:#00B5A5}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
.wrap{max-width:760px;margin:0 auto;padding:0 1.25rem}
header{border-bottom:1px solid var(--border);padding:1.1rem 0;position:sticky;top:0;background:rgba(13,15,20,.92);backdrop-filter:blur(8px);z-index:5}
header .wrap{display:flex;align-items:center;justify-content:space-between;gap:1rem}
.brand{font-weight:700;color:var(--text);font-size:1rem}
.brand span{color:var(--accent)}
nav a{color:var(--muted);font-size:.9rem;margin-left:1.1rem}
.hero{padding:3rem 0 1.5rem}
.hero h1{font-size:2rem;line-height:1.25;margin:0 0 .6rem}
.hero p{color:var(--muted);margin:0;font-size:1rem}
.list{padding:1rem 0 4rem;display:grid;gap:.9rem}
.card{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:1.25rem 1.4rem}
.card:hover{border-color:var(--accent)}
.card h2{font-size:1.1rem;margin:0 0 .4rem;line-height:1.35}
.card h2 a{color:var(--text)}
.card .meta{color:var(--muted);font-size:.8rem;margin:0 0 .5rem}
.card p.ex{color:var(--muted);font-size:.9rem;margin:0}
article{padding:2.5rem 0 4rem}
article h1{font-size:2rem;line-height:1.25;margin:0 0 .5rem}
article .meta{color:var(--muted);font-size:.85rem;margin:0 0 2rem;padding-bottom:1.25rem;border-bottom:1px solid var(--border)}
article h2{font-size:1.4rem;margin:2.25rem 0 .75rem;line-height:1.3}
article h3{font-size:1.12rem;margin:1.75rem 0 .6rem}
article p{margin:0 0 1.1rem}
article ul,article ol{margin:0 0 1.1rem;padding-left:1.3rem}
article li{margin-bottom:.4rem}
article img{max-width:100%;height:auto;border-radius:8px}
article blockquote{margin:0 0 1.1rem;padding:.6rem 0 .6rem 1rem;border-left:3px solid var(--accent);color:var(--muted)}
article hr{border:0;border-top:1px solid var(--border);margin:2rem 0}
code{background:var(--surface);border:1px solid var(--border);border-radius:4px;padding:.1rem .35rem;font-size:.88em;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
pre{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:1rem 1.15rem;overflow-x:auto;margin:0 0 1.2rem}
pre code{background:none;border:0;padding:0;font-size:.85rem;line-height:1.6}
.tablewrap{overflow-x:auto;margin:0 0 1.2rem}
table{border-collapse:collapse;width:100%;font-size:.9rem}
th,td{border:1px solid var(--border);padding:.55rem .7rem;text-align:left;vertical-align:top}
th{background:var(--surface)}
footer{border-top:1px solid var(--border);padding:2rem 0 3rem;color:var(--muted);font-size:.85rem}
footer a{color:var(--muted);text-decoration:underline}
.back{display:inline-block;color:var(--muted);font-size:.88rem;margin-bottom:1.5rem}
/* The back link moved out of the article element so importers stop pulling it
   into the post body. These two rules keep the rendered spacing identical to
   when it was inside: nav takes over the top padding, article drops its own.
   Keep literal angle-bracket tag names out of this comment - it ships inside
   the style block and makes the page source lie to any tag-matching check. */
.postnav{padding-top:2.5rem}
.postnav+article{padding-top:0}
@media(max-width:600px){.hero h1,article h1{font-size:1.55rem}}
`;

function shell({ title, description, canonical, body, ogType = "website" }) {
  return `<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${esc(canonical)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:type" content="${ogType}">
<meta property="og:url" content="${esc(canonical)}">
<meta property="og:image" content="${SITE}/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="alternate" type="application/rss+xml" title="${esc(NAME)}" href="${SITE}/rss.xml">
<style>${CSS}</style>
</head><body>
<header><div class="wrap">
  <a class="brand" href="/">Relay<span>Shield</span></a>
  <nav>
    <a href="/">Blog</a>
    <a href="https://api.relayshield.net/developers">Developers</a>
    <a href="/rss.xml">RSS</a>
  </nav>
</div></header>
${body}
<footer><div class="wrap">
  <p>${esc(NAME)} &mdash; <a href="https://api.relayshield.net/developers">API documentation</a> &middot; <a href="/rss.xml">RSS</a></p>
  <p>Questions: <a href="mailto:support@relayshield.net">support@relayshield.net</a></p>
</div></footer>
</body></html>`;
}

function indexPage() {
  const cards = POSTS.map(
    (p) => `<div class="card">
  <p class="meta">${esc(fmtDate(p.date))}</p>
  <h2><a href="/${esc(p.slug)}">${esc(p.title)}</a></h2>
  <p class="ex">${esc(p.excerpt)}</p>
</div>`
  ).join("\n");

  return shell({
    title: NAME,
    description: TAGLINE,
    canonical: SITE + "/",
    body: `<div class="wrap">
  <div class="hero"><h1>${esc(NAME)}</h1><p>${esc(TAGLINE)}</p></div>
  <div class="list">${cards}</div>
</div>`,
  });
}

function postPage(post) {
  // Tables in imported content need a scroll container so the page body never
  // scrolls horizontally on mobile.
  const body = post.html
    .replace(/<table/g, '<div class="tablewrap"><table')
    .replace(/<\/table>/g, "</table></div>");

  return shell({
    title: post.title + " | RelayShield",
    description: post.excerpt,
    canonical: `${SITE}/${post.slug}`,
    ogType: "article",
    // The back link sits OUTSIDE <article> deliberately. Importers and readers
    // treat <article> as the post body and take everything in it, so while this
    // link lived inside, Medium's importer pulled "<- All posts" into the top of
    // the imported story (seen 2026-08-03). It is site navigation, not article
    // content, so <nav> is also the correct semantics.
    body: `<div class="wrap">
  <nav class="postnav"><a class="back" href="/">&larr; All posts</a></nav>
  <article>
  <h1>${esc(post.title)}</h1>
  <p class="meta">${esc(fmtDate(post.date))}</p>
  ${body}
</article></div>`,
  });
}

function notFound() {
  return shell({
    title: "Not found | RelayShield",
    description: "That post could not be found.",
    canonical: SITE + "/",
    body: `<div class="wrap"><article>
  <h1>Post not found</h1>
  <p>That link doesn't match anything on this blog. It may have moved.</p>
  <p><a href="/">Browse all posts &rarr;</a></p>
</article></div>`,
  });
}

function rss() {
  const items = POSTS.map(
    (p) => `<item>
<title><![CDATA[${p.title}]]></title>
<link>${SITE}/${p.slug}</link>
<guid isPermaLink="true">${SITE}/${p.slug}</guid>
<pubDate>${new Date(p.date + "T00:00:00Z").toUTCString()}</pubDate>
<description><![CDATA[${p.excerpt}]]></description>
<content:encoded><![CDATA[${p.html}]]></content:encoded>
</item>`
  ).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title><![CDATA[${NAME}]]></title>
<link>${SITE}</link>
<description><![CDATA[${TAGLINE}]]></description>
<language>en</language>
${items}
</channel>
</rss>`;
}

function sitemap() {
  const urls = [`<url><loc>${SITE}/</loc></url>`]
    .concat(POSTS.map((p) => `<url><loc>${SITE}/${p.slug}</loc><lastmod>${p.date}</lastmod></url>`))
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

const html = (body, status = 200) =>
  new Response(body, {
    status,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=300",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
    },
  });

let OG_BYTES = null;
let DEV_OG_BYTES = null;

const xml = (body, type) =>
  new Response(body, {
    headers: { "Content-Type": `${type}; charset=utf-8`, "Cache-Control": "public, max-age=900" },
  });

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";

    if (path === "/") return html(indexPage());
    if (path === "/rss.xml" || path === "/feed") return xml(rss(), "application/rss+xml");
    if (path === "/sitemap.xml") return xml(sitemap(), "application/xml");
    // Card for api.relayshield.net/developers and its /guides/* pages. Hosted
    // here because API Gateway cannot reliably return binary to a crawler
    // sending Accept: */* -- see developers_og_image.js for the detail.
    if (path === "/developers-og.png") {
      if (!DEV_OG_BYTES) {
        const bin = atob(DEVELOPERS_OG_PNG_BASE64);
        DEV_OG_BYTES = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) DEV_OG_BYTES[i] = bin.charCodeAt(i);
      }
      return new Response(DEV_OG_BYTES, {
        headers: {
          "Content-Type": "image/png",
          "Cache-Control": "public, max-age=86400, immutable",
        },
      });
    }

    // Favicon. blog.relayshield.net served no icon at all, so every browser
    // tab and every card renderer fell back to the 134 KB og.png, which is the
    // same shield card on every post. SVG to match api.relayshield.net exactly,
    // so both origins show one mark from one source. /favicon.ico redirects
    // here for anything asking by convention.
    if (path === "/favicon.svg") {
      return new Response(FAVICON_SVG, {
        headers: {
          "Content-Type": "image/svg+xml",
          "Cache-Control": "public, max-age=604800",
        },
      });
    }

    if (path === "/favicon.ico" || path === "/apple-touch-icon.png" ||
        path === "/apple-touch-icon-precomposed.png") {
      return Response.redirect(`${SITE}/favicon.svg`, 302);
    }

    if (path === "/og.png") {
      // Decoded once per isolate, then reused across requests.
      if (!OG_BYTES) {
        const bin = atob(OG_PNG_BASE64);
        OG_BYTES = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) OG_BYTES[i] = bin.charCodeAt(i);
      }
      return new Response(OG_BYTES, {
        headers: {
          "Content-Type": "image/png",
          "Cache-Control": "public, max-age=86400, immutable",
        },
      });
    }

    if (path === "/robots.txt")
      return new Response(`User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n`, {
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      });

    const post = BY_SLUG.get(decodeURIComponent(path.slice(1)));
    if (post) return html(postPage(post));

    return html(notFound(), 404);
  },
};
