#!/usr/bin/env python3
"""Render bot_directories.json as the markdown the founder actually reads.

GENERATED, NEVER HAND-WRITTEN, and that is the whole point of it existing.
The founder reads a .md; the funnel reads the .json. Maintaining both by hand
is two files that must agree with nothing checking that they do, which is this
repo's most-repeated defect -- the four pattern tables, LAMBDA_MAP against the
invoke policy, the three route lists, the watchlist secret name. Generating one
from the other removes the class rather than managing it.

    python3 tools/bot_directories_md.py            # print
    python3 tools/bot_directories_md.py --write    # write bot_directories.md

Needs no AWS and no network.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "bot_directories.json"
OUT = ROOT / "bot_directories.md"

STATUS_LABEL = {
    "ready": "Not submitted",
    "submitted_unconfirmed": "SUBMITTED, NOT CONFIRMED",
    "submitted": "Submitted",
    "approved": "LIVE",
    "ranked_last_by_rule": "Not submitted (ranked last by rule)",
}

TYPE_LABEL = {
    "unverified": "UNVERIFIED -- nobody has looked",
    "catalogue": "Curated catalogue",
    "broker": "Broker selling posts -- DO NOT SUBMIT",
    "catalogue_and_broker": "Both: real catalogue AND sells posts",
    "telegram_native": "Telegram-native, not a web form",
}


def render() -> str:
    d = json.loads(SRC.read_text())
    out = []
    out.append("# Bot directories -- where `@relayshield_bot` gets submitted\n")
    out.append("**GENERATED from `bot_directories.json` by "
               "`tools/bot_directories_md.py`. Do not edit this file by hand** -- "
               "the next regeneration overwrites it, and the JSON is what the "
               "funnel counts from.\n")
    out.append(f"The link form is **`{d['link_form']}`**, and the suffix is not "
               "optional:\n")
    out.append("- A Mini App link carries `?startapp=<key>` and the Worker GATES it, "
               "so an unregistered key is downgraded and logs `unmatched:` -- "
               "recoverable later, because the unmatched row names it.")
    out.append("- A bot link carries `?start=SRC_<key>` and there is **no allowlist "
               "at all**. Any key is accepted and logged verbatim, so **no "
               "registration is needed anywhere.**")
    out.append("- **The unrecoverable mistake here is OMISSION.** A listing pointing "
               "at a bare `t.me/relayshield_bot` logs nothing, leaves no unmatched "
               "row, and is indistinguishable from organic `/start` traffic "
               "forever.\n")
    out.append("**Type-check every destination before submitting.** A curated "
               "catalogue and a broker selling posts are different things and "
               "audience size does not separate them -- and as BotsArchive shows, "
               "**they are not mutually exclusive.**\n")
    out.append("Count arrivals with:\n")
    out.append("```zsh")
    out.append("AWS_PROFILE=relayshield ~/.rsvenv/bin/python tools/source_arrivals.py --surface bot")
    out.append("```\n")

    out.append("## The running order\n")
    out.append("| # | Destination | Key | State | Type |")
    out.append("|---|---|---|---|---|")
    for r in d["routes"]:
        url = r.get("submit_url")
        dest = f"[{r['destination']}]({url})" if url else r["destination"]
        out.append(f"| {r['rank']} | {dest} | `{r['key']}` | "
                   f"{STATUS_LABEL.get(r.get('status'), r.get('status','?'))} | "
                   f"{TYPE_LABEL.get(r.get('route_type'), r.get('route_type','?'))} |")
    out.append("")

    out.append("## Why each one sits where it does\n")
    for r in d["routes"]:
        out.append(f"### {r['rank']}. {r['destination']}\n")
        out.append(f"**Key** `{r['key']}` · "
                   f"**State** {STATUS_LABEL.get(r.get('status'), r.get('status','?'))}"
                   + (f" · **Submitted** {r['submitted_at']}" if r.get("submitted_at") else ""))
        if r.get("submit_url"):
            out.append(f"\n**Submit at** <{r['submit_url']}>")
        out.append(f"\n**Link to give them**\n")
        out.append("```text")
        out.append(d["link_form"].replace("<key>", r["key"]))
        out.append("```\n")
        out.append(r.get("note", "") + "\n")

    out.append("---\n")
    out.append("**Every URL above is UNVERIFIED from the container** -- all of them "
               "are egress-blocked there, which is a fact about the container and "
               "not about the destination. The one-minute read is the founder's, "
               "and that is the same reason the web-front-door finding exists at all.\n")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write bot_directories.md")
    args = ap.parse_args()
    text = render()
    if args.write:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
